# Generated by Django 4.2.6 on 2023-11-03 19:00

from django.db import migrations, models
import django.db.models.deletion
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(
                max_length=100,
                unique=True,
                validators=[django.core.validators.RegexValidator(
                    message='Name must consist of letters, numbers, hyphens, and underscores only.',
                    regex='^[a-zA-Z0-9_-]+$'
                )]
            ),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='e_shop.category',
                to_field='name'
            ),
        ),
    ]
